### PR TITLE
Added stack compatiblility, compile and runs tests with LTS-5.4

### PR DESCRIPTION
**Pull request by lucamolteni**
A simple stack init generates this stack file that compiles without problem with the latest LTS 5.4

### CODE REVIEW

**Comment by lucamolteni** [comment]
Uhm... The travis build failed, but I can't see really why. Cabal should ignore the presence of a stack file.

**Comment by vincenthz** [comment]
The tests failed for another reason, which I'm having a hard time to track down;

I don't think there's any benefits to adding stack files to libraries; it's only useful for program where you want everyone to use the same basis of libraries, but for library which are supposed to build in many different package sets, it's probably harmful.

**Comment by lucamolteni** [comment]
How is it harmful? I'm really interested.

**Comment by mgsloan** [comment]
As long as your CI is running `cabal install`, then I don't see what the difference is.   Here's my view on why having it in the repo is helpful: https://www.reddit.com/r/haskell/comments/415vne/to_ship_stackyaml_or_not_to/

We have plans for making stack try different versions - https://github.com/commercialhaskell/stack/issues/1568 .  Once that's done, stack will be quite good at version ranges, because we will actually test them.

**Comment by vincenthz** [comment]
To clarify the 'harmful'; I think it send the message that the specific version of stackage that the stack.yaml file use would be preferred compared to what it should really be: many different set of library environment are supported.

Also, I don't think it add any value:

* `stack init` would generate the same file. there's no extra customisation in it.
* travis would not run any tests against the stack, leaving it for bit-rot
* I rarely/never use `stack` for general library that are supposed to work in a wide choice of env, leaving it for bit-rot more.

That said, I don't have that much strong filling against it

**Pull request closed without merging**
