### PR TITLE
Put brackets around assign statement inside if, if needed

### PR DESCRIPTION
**Pull request by dvekeman**
```
> pretty <$> parser stmt "if ((as = cells) != null) {}"
Right if (as = cells != null)
{
}
```

Assignment inside if should have bracket around it

### CODE REVIEW

**Comment by dvekeman** [comment]
I'm double checking this one

**Comment by vincenthz** [comment]
It would be nice to see if we could have a testing approach based on quickcheck.

1. generate random ast
2. pretty print
3. parse
4. check for equality

**Comment by dvekeman** [comment]
Something like this:

```
import Test.QuickCheck
...
prop_ParsePretty cu = parser compilationUnit (showPretty cu) == Right cu
  where types = cu::CompilationUnit
        showPretty = show . pretty
```

```
> quickCheck prop_ParsePretty
+++ OK, passed 100 tests.
```

**Comment by dvekeman** [comment]
Here is a first attempt: https://github.com/dvekeman/language-java/commit/f308f67903a630e5cfe5c7b8488645d0126afd3a

Notably the tests for Exp are currently failing (but haven't investigated yet)

```
> quickCheck prop_ParsePrettyExp
*** Failed! Falsifiable (after 2 tests):
BinOp (Lit (Int 1)) Mult (BinOp (BinOp (Lit (Int 0)) Mult (BinOp (Lit (String "m\GSCq.Wjg\232k")) Mult (Lit (String "!\244-\ESC\225")))) Mult (BinOp (BinOp (Lit (Int 0)) Mult (BinOp (Lit (String "I+{O\185")) Mult (Lit (Int (-1))))) Mult (Lit (String "\170Y\181T"))))
```

**Comment by vincenthz** [comment]
I would guess it's going to trip the parser/printer quite a lot. one of the best example is that the binary operations (+,-,*) are a train wreck in this package not handling precedence correctly.

**Pull request closed without merging**
